# use existing scripts to get HBonds, PiStacks, Ring
# use RdKit to generate SG, NumMethyl, NumRotors

from rdkit import Chem
from rdkit.Chem import rdMolDescriptors
import pandas as pd
import numpy
import os

# these work for a single molecule
from hbond import CalcHBondFoldability
from pipistack import CalcPiPiStackFoldability
from RingEntropy import CalcTotalRingFlexibility

def get_crest_entropy(file_path):
    """Extracts 'Sconf' or conformational entropy from CREST output."""
    if not os.path.exists(file_path): return None
    with open(file_path, 'r') as f:
        for line in f:
            # Looking for the entropy term in the CREST summary
            # if "= S(total)" in line or "Conformational Entropy" in line:
                # Adjusting split based on standard CREST output format
                # return float(line.split()[3])
                
            if "Sconf" in line or "Conformational Entropy" in line:
                # Adjusting split based on standard CREST output format
                return float(line.split()[2])    
    return None

BASE_PATH = "/home/annav/iocb/Crest-on-PL-REX-dataset"
TABLES_DIR = os.path.join(BASE_PATH, "tables")

path = f"{BASE_PATH}/data/02_data/020_structures_sdf"

ligands = [f for f in os.listdir(path)]
data = []

sg_pattern = Chem.MolFromSmarts('[CX3](=[O,S])[O,N]')
methyl_pattern = Chem.MolFromSmarts('[CH3]')
nonstrict_rotor_query = Chem.MolFromSmarts('[!$(*#*)&!D1]-!@[!$(*#*)&!D1]')

for lig in ligands:
    # 1. Paths to log files (Adjust filenames like 'xtb.log' to match yours)
    # path_crest_xtb = f"{BASE_PATH}/data/01_data/crest_best_structures_xtb_2/{lig}/{lig}_xtb_log.txt"
    name = lig.split('.')[0]
    mol = Chem.MolFromMolFile(f"{path}/{lig}")
    target, ligand = name.split("__")
    path_gfn2_new_c2 = f"{BASE_PATH}/data/01_data/gfn2_new/{name}/crest2/{name}_log.txt"
    
    if mol is None: continue
    
    h_bonds = CalcHBondFoldability(mol)
    pipi = CalcPiPiStackFoldability(mol)
    ring = CalcTotalRingFlexibility(mol)
    
    # generated by RdKit
    numRot = len(mol.GetSubstructMatches(nonstrict_rotor_query))
    # amide, ester, and thioamide
    SG = len(mol.GetSubstructMatches(sg_pattern))
    numMethyl = len(mol.GetSubstructMatches(methyl_pattern))
    
    # Import the calculated Sconf
    s_conf = get_crest_entropy(path_gfn2_new_c2)
    
    #np.log1p(NumRotors)+np.log1p(NumMethyl)+np.log1p(Ring)+np.log1p(SG)+np.log1p(HBond)+np.log1p(PiStack)
    data.append({
        'Target': target, 
        'Ligand': ligand,
        'NumRotors': numRot,
        'NumMethyl': numMethyl,
        'Ring': ring, 
        'SG': SG, 
        'HBond': h_bonds, 
        'PiStack': pipi,
        'ConfEntropy': s_conf
    })
    
df = pd.DataFrame(data)
df.sort_values(by=['Target', 'Ligand'], inplace=True)
df.to_csv(os.path.join(TABLES_DIR, 'lm5_features.csv'), index=False)